[project]
name = "data-acquisition-example"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "acsys",
  "acsys[settings]",
  "pyqt6>=6.10.2",
]

[project.scripts]
# from demo import main; main()
demo = "demo:main"

[tool.uv]
package = true

[tool.uv.sources]
acsys = { git = "https://github.com/fermi-ad/acsys-python", rev = "v0.12.9" }
