[project]
name = "data-acquisition-example"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "acsys @ https://www-bd.fnal.gov/pip3/acsys/acsys-0.12.8.tar.gz",
  "acsys[settings] @ https://www-bd.fnal.gov/pip3/acsys/acsys-0.12.8.tar.gz",
  "pyqt6>=6.10.2",
]

[project.scripts]
# from demo import main; main()
demo = "demo:main"

[tool.uv]
package = true
